version: '3'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - acadabrain
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    env_file:
      - .env
    networks:
      - acadabrain

networks:
  acadabrain:
