services:
  acada-brain-api-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 3001:3001
    environment:
      - PORT=3000
      - NODE_ENV=production
    volumes:
      - ./src:/usr/src/app/src
  acada-brain-db-prod:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=acada_brain
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
      - MYSQL_TCP_PORT=3307
